### PR TITLE
Add support for 3.63+ FW

### LINKED ISSUE #36: Crashes with use of the 3.65 enzo
It was working on 3.60 enzo and recently updated. Just wondering if anyone figured out a fix for this or patiently wait for the update :)

### PR DESCRIPTION
**Pull request by al3xtjames**
This PR adds 3.63+ FW support to the psvgamesd driver. As some NIDs
have changed since 3.61, the `ksceKernelGetModuleInfo` function is now
resolved at runtime instead of linking the SceModulemgrForKernel stub.
Existing function hooks and patches have been checked and should work
on 3.60-3.70. Dumping and mounting have been tested on 3.65. The only
noted issue is #37, which is not specific to 3.65 and is out of the
scope of this PR. Fixes #36.

### CODE REVIEW

**Comment by al3xtjames** [comment]
~~Partially related: are key1/key2/signature (in the PSV header, taken from the CMD56 response) supposed to be consistent? It changes when dumping the same cartridge after a reboot - not sure if this is intentional, or a 3.65-only bug.~~

As expected, the offset for the CMD56 (sensitive data) buffer in SceSblGcAuthMgrDrmBBForDriver changed (addressed in the latest commit).

**Comment by motoharu-gosuto** [comment]
@al3xtjames 
Hi friend. Thank you for the update and sorry for late response!
Please let me know if this is a final pull request (At the moment I have no ability to test this on vita).
If yes -  I will merge this.

**Comment by al3xtjames** [comment]
Thanks for the reply. There are still some things that need to be updated (need to check if other module offsets changed; so far dumping works, but mounting needs some work). I'm fairly busy at the moment, so this may take some time. I will remove the WIP tag when it's ready.

**Comment by al3xtjames** [comment]
Offsets for function hooks/patches were checked:

`taiHookFunctionImportForKernel`:
 - SceSdifForDriver (0x96D306FA)
    - [x] 0x175543D2 (`mmc_write_hook`) - same on 3.60-3.69
    - [x] 0x6F8D529B (`mmc_read_hook`) - same on 3.60-3.69
    - [x] 0xB9593652 (`sd_read_hook`) - same on 3.60-3.69
    - [x] 0xE0781171 (`sd_write_hook`) - same on 3.60-3.69
 - SceSblGcAuthMgrGcAuthForDriver (0xC6627F5E)
    - [x] 0x68781760 (`gc_cmd56_handshake_hook`) - same on 3.60-3.69
 - SceThreadmgrForDriver (0xE2C40624)
    - [x] 0x70627F3A (`fast_mutex_lock_hook`) - same on 3.60-3.69
    - [x] 0xDB395782 (`fast_mutex_unlock_hook`) - same on 3.60-3.69
    - [x] 0xF4EE4FA9 (`sys_wide_time_hook`) - same on 3.60-3.69

`taiHookFunctionExportForKernel`:
 - SceSblGcAuthMgrDrmBBForDriver (0x1926B182)
   - [x] 0xBB451E83 (`clear_sensitive_data_hook`) - same on 3.60-3.69
 - SceSdifForDriver (0x96D306FA)
   - [x]  0xC1271539 (`init_sd_hook`) - same on 3.60-3.69

`taiHookFunctionOffsetForKernel`:
 - SceSdif
   - [x] 0xC84 (`get_insert_state_hook`) - same on 3.60-3.69
   - [x] 0x17E8 (`send_command_hook`) - same on 3.60-3.69

Offsets for `module_get_offset` and `taiInjectDataForKernel` (as well as any
patches) also appear to be valid for 3.60-3.69. The only exception is the
offset of the aforementioned CMD56 sensitive data buffer, which changed in
3.63.

**Comment by al3xtjames** [comment]
I've attached a build of the driver (with `ENABLE_DEBUG_LOG` set) for
testing. It should work on 3.60-3.68; please check if it's functional
on ~~3.60~~/3.61/3.63/3.67/~~3.68~~.

[psvgamesd.skprx.zip](https://github.com/motoharu-gosuto/psvgamesd/files/2730167/psvgamesd.skprx.zip)

**Comment by motoharu-gosuto** [comment]
@al3xtjames
Thanks for the work. Unfortunately I can not check it personally now.
It might be a good idea to organize some testing but there should be people willing to do it.
Do you know anyone in particular?

**Comment by al3xtjames** [comment]
I talked to pool7 on the VGPC Discord. They reported success with this version of the plugin on a 3.60 PSTV and a 3.68 Vita - the hashes of the produced dumps matched. I think this is sufficient (for now, at least). Other 3.6x firmware versions *should* also work (module offsets/etc changed with 3.63 and appear to have remained the same since then).

**Comment by motoharu-gosuto** [comment]
@al3xtjames
Great. Thanks for testing.
As we agreed before - I have now reviewed the PR. Here are my comments:

commit: ecb27e8934b622cd36c4d8c544f2b600052f79ab
please remove module.h. it is part of taihen and should not be inside psvgamesd repo.
https://github.com/yifanlu/taiHEN/blob/master/module.h

commit: df85ba091e3bdee57f109026ac0859cf0451548f
I am not following closely the latest changes in SDK, but why did you delete vita-libs-gen call from build.h?
Is that because Sdif NIDs were added to latest SDK?
Also what would happen with different nids on different versions of FW. How does vitasdk handle this?
I would also suggest to check the very latest version. Sdif module names in db.yml  should have been changed significantly.

commit: 3c25ec9950e3dfcd9bad774f9e37ada0b930bfcb
in file functions.c
please rename _ksceKernelGetModuleInfo as well as ksceKernelGetModuleInfo_t to sceKernelGetModuleInfoForKernel to maintain same naming convention.

After that - please build a new version in Release without ENABLE_DEBUG_LOG.
Do a final test, and attach the archive here.

Then I will merge PR and create a new release.
Again - thanks for the work!

**Comment by al3xtjames** [comment]
Thanks for the review. In regards to your suggestions:

Addition of module.h:
This header is not included in the taiHEN release tarball used by vitasdk (only taihen.h is included). It looks like other projects ([gamecard-microsd](https://github.com/xyzz/gamecard-microsd/blob/6f05133ef462feeb3c301eaa6a9a68a85582e552/driver/main.c#L55), [vitashell](https://github.com/TheOfficialFloW/VitaShell/blob/df1fea2cb81a36e80ed99755136e4431cfbfe1b0/modules/kernel/main.c#L34-L35)) manually define the function prototypes, so I will do the same (will add them to functions.h and remove the copy of module.h).

Removal of extra.yml/vita-libs-gen call:
Yes, I removed this as vitasdk now has the SceSdif NIDs in db.yml. These names should match with the latest versions of vitasdk. The only NID that changed was SceSdif's module NID, which shouldn't matter (NIDs for the SceSdifForDriver library and its functions have not changed). However, SceKernelModulemgr had fairly significant changes since 3.60 (module, library (SceModulemgrForKernel), and function NIDs changed), which is why I used `module_get_export_func` for resolving `ksceKernelGetModuleInfo` (in commit 
3c25ec9)). I will update the function pointer type/name to match the existing convention.

Also: It appears that vitasdk now has definitions for the SHA-256 structures/functions (from SceKernelUtilsForDriver) as well as the fast mutex/condition variable functions (from SceThreadmgrForDriver). Is it OK if I remove these from functions.h and use the definitions from vitasdk?

**Comment by motoharu-gosuto** [comment]
@al3xtjames 
Agreed on module.h
Also feel free to use SceKernelUtilsForDriver and SceThreadmgrForDriver functions.
I hooked them as they are because at that time they were not available in vitasdk.
Great that somebody has finally added the stuff that I reversed.

**Comment by al3xtjames** [comment]
Rebased and cleaned up the commits. Release build attached:

[psvgamesd.skprx.zip](https://github.com/motoharu-gosuto/psvgamesd/files/2819006/psvgamesd.skprx.zip)

**Comment by motoharu-gosuto** [comment]
@al3xtjames 
I had reviewed everything. Great work. I think we are almost there.
I have couple of new questions.

In functions.h you have left these prototypes.
ksceKernelRegisterSysEventHandler
ksceKernelUnregisterSysEventHandler
Is this because you are using stubs from vitasdk, but prototypes in vitasdk are different from mine?

sector_api.h
Same questions as in functions.h
There are these prorotypes left:
ksceSdifGetSdContextGlobal
ksceSdifGetSdContextPartValidateMmc
ksceSdifGetSdContextPartValidateSd
ksceSdifGetSdContextPartValidateSdio
ksceSdifGetCardInsertState1
ksceSdifGetCardInsertState2
ksceSdifInitializeMmcDevice
ksceSdifInitializeSdDevice
ksceSdifReadSectorMmc
ksceSdifReadSectorSd
ksceSdifWriteSectorMmc
ksceSdifWriteSectorSd
ksceSdifGetCID

app/src/main.c
Has changed. I see you have fixed some edge cases for strings. Good.
Since it has changed - please also provide a build of user app.

In driver/mmc_reg.h
You have changed MMC_CID_PNM_SET from strncpy to memcpy. Why is that change required?
This change changes the behavior of the macro.

driver/sd_reg.h
You have changed SD_CID_OID_SET and SD_CID_PNM_SET. Same questions.

Minor improvement request.
In functions.c
Please introduce #define for each data_buffer_offset value for different firmware versions.

Thanks!

**Comment by al3xtjames** [comment]
> In functions.h you have left these prototypes.
> ksceKernelRegisterSysEventHandler
> ksceKernelUnregisterSysEventHandler
> Is this because you are using stubs from vitasdk, but prototypes in vitasdk are different from mine?

The NIDs for these functions are present in vitasdk (stubs are generated), but there aren't headers with these function prototypes included, which is why I kept these. This also applies to the SceSdif functions in sector_api.h.

> In driver/mmc_reg.h
> You have changed MMC_CID_PNM_SET from strncpy to memcpy. Why is that change required?
> This change changes the behavior of the macro.

Sorry - I'll revert this. GCC 8 warns of potential output truncation, but it's intentional in this case (and only used with specific literals).

**Comment by al3xtjames** [comment]
Addressed the remaining issues in the latest patchset (reverted macro changes & added definitions for buffer offsets). Builds of the plugin and app are attached:

[psvgc.vpk.zip](https://github.com/motoharu-gosuto/psvgamesd/files/2834519/psvgc.vpk.zip)
[psvgamesd.skprx.zip](https://github.com/motoharu-gosuto/psvgamesd/files/2834502/psvgamesd.skprx.zip)

**Comment by motoharu-gosuto** [comment]
@al3xtjames 
Merging now and making a new release.
Feel free to advertise new release to VGPC folks or any others interested.
Thank you!

**Pull request merged**
